### ISSUE TITLE
Organize the code by creating separate css files instead of using <style> tag

### ISSUE THREAD

**Issue by marsian83** [loganlokku/uki-website#17]
Using the <style> tag to write css tags may not always be considered the best of practices so I reckoned we could organize the code a bit more by separating the stylings into their own css files and putting all these css files into one directory.

Also I've notices some errors within the <style> tag css as well which could also be fixed.

**Comment by marsian83** [comment]
Please assign this issue to me under hacktoberfest

**Comment by marsian83** [comment]
#18

**Comment by loganlokku** [comment]
.
